[
  {
    "type": "tweet",
    "body": "we gucci ;)",
    "id": "04qVtFB9",
    "author": "Nico",
    "isLiked": false,
    "retweetCount": 0,
    "replyCount": 0,
    "likeCount": 0,
    "someLikes": 0,
    "createdAt": "2019-12-05T04:40:23.901Z"
  },
  {
    "type": "reply",
    "parent": "Yvydgitt",
    "body": "we should be good<br><strong>Reply to:</strong> @Nico<p>are we good?<br><strong>Retweet from:</strong> @Nico<p>test  to make sure everything is fine :3</p></p>",
    "id": "Y6swXZXd",
    "author": "Nico",
    "isLiked": false,
    "retweetCount": 0,
    "replyCount": 0,
    "likeCount": 0,
    "someLikes": 0,
    "createdAt": "2019-12-05T04:40:13.675Z"
  },
  {
    "type": "retweet",
    "parent": "bu7xnxvc",
    "body": "are we good?<br><strong>Retweet from:</strong> @Nico<p>test  to make sure everything is fine :3</p>",
    "id": "Yvydgitt",
    "author": "Nico",
    "isLiked": false,
    "retweetCount": 0,
    "replyCount": 1,
    "likeCount": 0,
    "someLikes": 0,
    "createdAt": "2019-12-05T04:40:03.733Z"
  },
  {
    "type": "tweet",
    "body": "test  to make sure everything is fine :3",
    "id": "bu7xnxvc",
    "author": "Nico",
    "isLiked": false,
    "retweetCount": 1,
    "replyCount": 0,
    "likeCount": 0,
    "someLikes": 0,
    "createdAt": "2019-12-05T04:39:38.533Z"
  },
  {
    "type": "tweet",
    "body": " mhhjh",
    "id": "NWMcBazV",
    "author": "Nico",
    "isLiked": false,
    "retweetCount": 0,
    "replyCount": 0,
    "likeCount": 0,
    "someLikes": 0,
    "createdAt": "2019-12-03T20:18:16.713Z"
  },
  {
    "type": "reply",
    "parent": "Tp1bAyi5",
    "body": "gjgkkh<br><strong>Reply to:</strong> @Nico<p>ytjuttjut</p>",
    "id": "-cpfkpGb",
    "author": "Nico",
    "isLiked": false,
    "retweetCount": 0,
    "replyCount": 0,
    "likeCount": 0,
    "someLikes": 0,
    "createdAt": "2019-12-03T19:47:51.099Z"
  },
  {
    "type": "tweet",
    "body": "ytjuttjut",
    "id": "Tp1bAyi5",
    "author": "Nico",
    "isLiked": false,
    "retweetCount": 0,
    "replyCount": 1,
    "likeCount": 0,
    "someLikes": 0,
    "createdAt": "2019-12-03T19:42:19.046Z"
  },
  {
    "type": "tweet",
    "body": "weff",
    "id": "JOvbwa1m",
    "author": "Nico",
    "isLiked": false,
    "retweetCount": 0,
    "replyCount": 0,
    "likeCount": 0,
    "someLikes": 0,
    "createdAt": "2019-12-03T05:17:22.175Z"
  },
  {
    "type": "reply",
    "parent": "7jczyudu",
    "body": "byeeeeeeeeeeeeeeeee<br><strong>Reply to:</strong> @Nico<p>heyyyyyyyyyyyyyyyyyyyyy<br><strong>Retweet from:</strong> @Nico<p>yooooooooooooooooooooooooooooo</p></p>",
    "id": "WT4Y966I",
    "author": "Nico",
    "isLiked": false,
    "retweetCount": 0,
    "replyCount": 0,
    "likeCount": 0,
    "someLikes": 0,
    "createdAt": "2019-12-02T21:14:09.853Z"
  },
  {
    "type": "retweet",
    "parent": "-Z6nXMFY",
    "body": "heyyyyyyyyyyyyyyyyyyyyy<br><strong>Retweet from:</strong> @Nico<p>yooooooooooooooooooooooooooooo</p>",
    "id": "7jczyudu",
    "author": "Nico",
    "isLiked": false,
    "retweetCount": 0,
    "replyCount": 1,
    "likeCount": 0,
    "someLikes": 0,
    "createdAt": "2019-12-02T21:14:00.677Z"
  },
  {
    "type": "tweet",
    "body": "yooooooooooooooooooooooooooooo",
    "id": "-Z6nXMFY",
    "author": "Nico",
    "isLiked": false,
    "retweetCount": 1,
    "replyCount": 0,
    "likeCount": 0,
    "someLikes": 0,
    "createdAt": "2019-12-02T21:13:46.712Z"
  },
  {
    "type": "reply",
    "parent": "3klP9xyy",
    "body": "reply 2<br><strong>Reply to:</strong> @Nico<p>post</p>",
    "id": "hAqWxlFk",
    "author": "Nico",
    "isLiked": false,
    "retweetCount": 0,
    "replyCount": 0,
    "likeCount": 0,
    "someLikes": 0,
    "createdAt": "2019-12-01T03:36:00.446Z"
  },
  {
    "type": "reply",
    "parent": "3klP9xyy",
    "body": "testing reply :3<br><strong>Reply to:</strong> @Nico<p>post</p>",
    "id": "9Iwdwpm1",
    "author": "Nico",
    "isLiked": false,
    "retweetCount": 0,
    "replyCount": 0,
    "likeCount": 0,
    "someLikes": 0,
    "createdAt": "2019-12-01T03:17:06.812Z"
  },
  {
    "type": "tweet",
    "body": "post",
    "id": "3klP9xyy",
    "author": "Nico",
    "isLiked": false,
    "retweetCount": 0,
    "replyCount": 2,
    "likeCount": 0,
    "someLikes": 0,
    "createdAt": "2019-12-01T03:06:37.142Z"
  },
  {
    "type": "reply",
    "parent": "G3WwG_DM",
    "body": "wefwe",
    "id": "kJbytroS",
    "author": "Nico",
    "isLiked": false,
    "retweetCount": 0,
    "replyCount": 0,
    "likeCount": 0,
    "someLikes": 0,
    "createdAt": "2019-12-01T03:05:35.021Z"
  },
  {
    "type": "reply",
    "parent": "N32fE8Y9",
    "body": "ewfwef",
    "id": "G3WwG_DM",
    "author": "Nico",
    "isLiked": false,
    "retweetCount": 0,
    "replyCount": 1,
    "likeCount": 0,
    "someLikes": 0,
    "createdAt": "2019-12-01T03:05:19.543Z"
  },
  {
    "type": "retweet",
    "parent": "B0r6w3A8",
    "body": "test retweet foreal this time\n\nPlease work :(((<br><strong>Retweet from:</strong> @Nico<p>testing retweet :( please work :(((((</p>",
    "id": "N32fE8Y9",
    "author": "Nico",
    "isLiked": false,
    "retweetCount": 0,
    "replyCount": 1,
    "likeCount": 0,
    "someLikes": 0,
    "createdAt": "2019-12-01T03:02:02.789Z"
  },
  {
    "type": "retweet",
    "body": "testing retweet :( please work :(((((",
    "parent": "f_7d0Rva",
    "id": "B0r6w3A8",
    "author": "Nico",
    "isLiked": false,
    "retweetCount": 1,
    "replyCount": 0,
    "likeCount": 0,
    "someLikes": 0,
    "createdAt": "2019-12-01T02:35:28.781Z"
  },
  {
    "type": "tweet",
    "body": "test for accessing a specific tuit body :(",
    "id": "1rXpy98f",
    "isLiked": false,
    "retweetCount": 0,
    "replyCount": 0,
    "likeCount": 0,
    "someLikes": 0,
    "createdAt": "2019-12-01T02:11:30.269Z"
  },
  {
    "type": "tweet",
    "body": "test for accessing the first element of the db :(",
    "id": "f_7d0Rva",
    "isLiked": false,
    "retweetCount": 1,
    "replyCount": 0,
    "likeCount": 0,
    "someLikes": 0,
    "createdAt": "2019-12-01T02:07:40.628Z"
  },
  {
    "type": "tweet",
    "body": "yayyy you are :')))",
    "id": "qLjWVfBZ",
    "isLiked": false,
    "retweetCount": 0,
    "replyCount": 0,
    "likeCount": 0,
    "someLikes": 0,
    "createdAt": "2019-12-01T02:05:56.721Z"
  },
  {
    "type": "tweet",
    "body": "are you added as the first element? :(",
    "id": "6z3POYEF",
    "isLiked": false,
    "retweetCount": 0,
    "replyCount": 0,
    "likeCount": 0,
    "someLikes": 0,
    "createdAt": "2019-12-01T02:05:43.679Z"
  },
  {
    "type": "tweet",
    "body": "are you working?",
    "id": "sOUjTNX9",
    "isLiked": false,
    "retweetCount": 0,
    "replyCount": 0,
    "likeCount": 0,
    "someLikes": 0,
    "createdAt": "2019-11-29T07:43:59.329Z"
  },
  {
    "type": "tweet",
    "body": "tell me you are working :(",
    "id": "9-9dpoW1",
    "isLiked": false,
    "retweetCount": 0,
    "replyCount": 0,
    "likeCount": 0,
    "someLikes": 0,
    "createdAt": "2019-12-01T02:03:12.072Z"
  },
  {
    "type": "tweet",
    "body": "are you really working? :')",
    "id": "KUGRHMFf",
    "isLiked": false,
    "retweetCount": 0,
    "replyCount": 0,
    "likeCount": 0,
    "someLikes": 0,
    "createdAt": "2019-12-01T02:04:00.116Z"
  },
  {
    "type": "tweet",
    "body": "you are!!! I'm so happy",
    "id": "auleCgVb",
    "isLiked": false,
    "retweetCount": 0,
    "replyCount": 0,
    "likeCount": 0,
    "someLikes": 0,
    "createdAt": "2019-12-01T02:04:17.556Z"
  }
]