POST http://localhost:3000/users
Content-Type: application/json

{
    "user": "Nico",
    "password": "hola",
    "fName": "Nicola",
    "lName": "Folchi",
    "email": "nico@hotmail.com"
}

###

GET http://localhost:3000/login
Content-Type: application/json

{
    "user": "Nico",
    "password": "hola"
}

