POST http://localhost:3000/users
Content-Type: application/json

{
    "user": "Nico",
    "password": "hola",
    "fName": "Nicola",
    "lName": "Folchi",
    "email": "nico@hotmail.com"
}

###

GET http://localhost:3000/login
Content-Type: application/json

{
    "user": "Nico",
    "password": "hola"
}
###

GET http://localhost:3000/getToken
Content-Type: application/json

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "user": "1273",
    "password": ""
}

###

GET http://localhost:3000/tuits
Content-Type: application/json
withCredentials: true

###

PUT http://localhost:3000/tuits/RJmYfLol
Content-Type: application/json
withCredentials: true

{
    "rating": 2,
    "review": "sucked balls"
}
