POST http://localhost:3000/users
Content-Type: application/json

{
    "user": "Nico",
    "password": "hola",
    "fName": "Nicola",
    "lName": "Folchi",
    "email": "nico@hotmail.com"
}

###

GET http://localhost:3000/login
Content-Type: application/json

{
    "user": "Nico",
    "password": "hola"
}
###

GET http://localhost:3000/getToken
Content-Type: application/json

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "user": "1273",
    "password": ""
}

###

GET http://localhost:3000/tuits
Content-Type: application/json
withCredentials: true

###

DELETE http://localhost:3000/tuits/DZKxd9sA
Content-Type: application/json
withCredentials: true


###

POST http://localhost:3000/changePassword
Content-Type: application/json
withCredentials: true

{
    "previousPassword": "test123",
    "newPassword": "test1234",
    "username": "test1"
}
